### ISSUE TITLE
Question regarding this utility

### ISSUE THREAD

**Issue by gabn88** [arskom/pyubl#1]
Hi,

I have a few questions regarding this utility:

1. Can I use it commercially? 
2. Can I create an UBL XML file from python/Django objects? Is this the best utility to do this, or how would you do this?

Thank you for your answer :)

**Comment by gabn88** [comment]
Also trying to install this module with pip:

pip install git+https://github.com/arskom/pyubl does not download the xsd files... is there a trick to do this?

**Comment by plq** [comment]
hey! This answer is two years late, but here it is :)

1. See license
2. I don't know about django but it can map xml documents spyne models.

Best,

**Comment by gabn88** [comment]
No problem, figured it out :)
